---

include:

  - project: "saltbox/ci-lib"
    file: "mirror-repo.yml"

  - project: 'saltbox/ci-lib'
    file: 'close-github-pr.yml'


variables:
  NODE_IMAGE: "node:22.18.0"
  YARN_CACHE_FOLDER: "./yarn_cache/"


cache:
  paths:
    - "$YARN_CACHE_FOLDER"


Build package:
  image: "$NODE_IMAGE"
  stage: build
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 day


Upload package:
  image: "$NODE_IMAGE"
  stage: deploy
  before_script:
    - yarn install --frozen-lockfile
    - |
      cat > .npmrc <<EOF
      //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken = "${CI_JOB_TOKEN}"
      @saltbox:registry = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
      EOF
  script:
    - yarn version --new-version $(echo "$CI_COMMIT_TAG" | sed 's/^v//') --no-git-tag-version
    - yarn publish
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_TAG_PATTERN


Mirror Repository:
  extends: .mirror-repo
  stage: build


Check for GitHub PR to close:
  extends: .close-github-pr
  stage: build
